Feature/implement authentication section on header and sidemenu
zinbac000/react-elearning pull request #5
Opened 2020-08-07 03:11 UTC by hoanghai1212

Apply UserAuth to Header, add style for Dropdown component

2020-08-07 04:01 UTC, zinbac000 requested changes

2020-08-07 04:01 UTC, zinbac000 commented on src/components/Auth/UserAuth/UserAuth.js
> +              <Button className={`${classes.Button} ${classes.LoginBtn}`} onClick={this.handleLogin}>
From now on, we will just use array for multiple classes for consistentcy

2020-08-07 04:01 UTC, zinbac000 commented on src/components/Auth/UserAuth/UserAuth.module.scss
> +  min-width: 100px;
With CSS styles, we will split them into groups:
- Positioning. (for ex: position, top, left, z-index) 
- Display & Box Modal. (for ex: display, flexbox, margin, padding, width, height, border, ...)
- Text (for ex: fonts, line-height, color...)
- The others.
P/S: If a group has too much property, you can split them into smaller related group for readability

2020-08-07 04:01 UTC, zinbac000 commented on src/components/Auth/UserMenu/UserMenu.js
> +        <RightOutlined
With Icon, i remember you can pass them className, we just make inline style when it is really hard to make className

2020-08-07 04:01 UTC, zinbac000 commented on src/components/Auth/UserMenu/UserMenu.module.scss
> +  display: flex;
Restructure css properties base on what i recommended

2020-08-07 04:01 UTC, zinbac000 commented on src/components/Auth/UserMenu/UserMenuBody/UserMenuBody.js
> +        <div className={classes.UserSection__wrapper}>
className should be PascalCase.

2020-08-07 04:01 UTC, zinbac000 commented on src/components/Auth/UserMenu/UserMenuBody/UserMenuBody.js
> +          {this.userNavLink.map((section, index) => {
Split this map to a variable in render function or a method in the component for readability

2020-08-07 04:01 UTC, zinbac000 commented on src/components/Auth/UserMenu/UserMenuBody/UserMenuBody.module.scss
> +  &__heading {
no camelCase className

2020-08-07 04:01 UTC, zinbac000 commented on src/components/Auth/UserNav/UserNav.js
> +                <a className={classes.UserSection__navlink} href="#">
no camelCase class

2020-08-07 04:01 UTC, zinbac000 commented on src/components/Auth/UserNav/UserNav.module.scss
> +  margin-left: 16px;
restructure css properties

2020-08-07 04:01 UTC, zinbac000 commented on src/components/Auth/UserMenu/UserMenuBody/UserMenuBody.js
> +              <div key={index}>
you don't need to have a redundant div to wrap your elements because this will make our html structure become complex. Instead you can use Fragment component of React or just <>//Your components</>.
For example:
     <key={index}>
             -List             
             -Divider
     </>

2020-08-07 04:01 UTC, zinbac000 commented on src/components/Auth/UserMenu/UserMenuBody/UserMenuBody.js
> +            style={{ color: 'white', fontSize: '12px' }}
use Classnam for this Icon

2020-08-07 04:01 UTC, zinbac000 commented on src/components/Auth/UserNav/UserNav.js
> +    <Menu>
You can remove the Menu component because menu usually go with Menu.Item. But you use List so there is no reason to use Menu anymore.

2020-08-07 04:01 UTC, zinbac000 commented on src/components/MainLayout/Header/Header.js
> +            <Menu>
Remove Menu component here, just you List.

2020-08-07 04:01 UTC, zinbac000 commented on src/components/MainLayout/Header/Header.js
> +              <Menu>
Remove Menu component.

2020-08-08 04:29 UTC, hoanghai1212 commented on src/components/Auth/UserAuth/UserAuth.js
> +              <Button className={`${classes.Button} ${classes.LoginBtn}`} onClick={this.handleLogin}>
done

2020-08-08 04:35 UTC, hoanghai1212 commented on src/components/Auth/UserAuth/UserAuth.module.scss
> +  min-width: 100px;
done

2020-08-08 05:15 UTC, hoanghai1212 commented on src/components/Auth/UserMenu/UserMenu.js
> +        <RightOutlined
done

2020-08-08 05:15 UTC, hoanghai1212 commented on src/components/Auth/UserMenu/UserMenu.module.scss
> +  display: flex;
done

2020-08-08 05:19 UTC, hoanghai1212 commented on src/components/Auth/UserMenu/UserMenuBody/UserMenuBody.js
> +              <div key={index}>
done

2020-08-08 07:19 UTC, hoanghai1212 commented on src/components/Auth/UserNav/UserNav.js
> +    <Menu>
done

2020-08-08 07:19 UTC, hoanghai1212 commented on src/components/MainLayout/Header/Header.js
> +            <Menu>
done

2020-08-08 07:19 UTC, hoanghai1212 commented on src/components/MainLayout/Header/Header.js
> +              <Menu>
done

2020-08-08 07:50 UTC, hoanghai1212 commented
all issues comment are fixed

2020-08-10 11:51 UTC, zinbac000 approved these changes
changes ok

2020-08-10 11:52 UTC, merged